# Numpy review homework

1. Make a numpy matrix from a Python list of lists...

In [14]:
import numpy as np
lst = [[1,2,3], ["This", "is", "the 2nd", "list"], [5,4,6]]
lt = [ [[1,2,3], [0,5,4], [5,4,6]], [[1,2,3], [0,5,4], [5,4,6]] ]

mtrix = np.array(lt)
mtrix
#type(mtrix)

array([[[1, 2, 3],
        [0, 5, 4],
        [5, 4, 6]],

       [[1, 2, 3],
        [0, 5, 4],
        [5, 4, 6]]])

2. Make a 3D numpy matrix from a Python list of lists of lists!

In [15]:
mtrix.T
mtrix.shape


(2, 3, 3)

3. Create a 5x3 array of Gaussian random numbers. 

In [16]:

noise = 3+np.random.randn(5,3)*.25
noise

array([[2.41482983, 2.86263618, 3.27521452],
       [3.24173904, 3.37258906, 2.62098773],
       [3.20305449, 2.65709843, 2.95488505],
       [2.72285202, 2.80506928, 3.1157146 ],
       [3.57374693, 3.12167256, 2.80061906]])

3.065904766609514
2.955260036315778
2.758415901857716
2.9255984975398177
3.0451847260828746
2.8075129112308845
3.404141995235628
2.9473805941822118
2.968260370530747
3.1454309840403285
3.4694309354660113
3.424757659886611
2.659553435573416
3.0343483271554454
3.016193949495592


4. Write a script to go through the array created in 3. and announce (print) the value and its row and column indexes.

Hint: Use nested `for` loops - one to loop through the rows and one to loop through the columns.

In [17]:
for i in range(noise.shape[0]) :
    for j in range(noise.shape[1]):
        print(noise[i,j])
###explain

2.4148298253660956
2.86263617853444
3.2752145229232514
3.2417390440819194
3.37258905933259
2.6209877264780164
3.203054486345553
2.657098426030127
2.9548850497003096
2.7228520217367524
2.805069279553562
3.115714600913683
3.5737469274626226
3.1216725646619965
2.800619061065684


5. Make an new array out of your random numbers such that the mean is 10 and the standard deviation is 3.

In [18]:
matrix = np.random.normal(10, 3)
matrix

6.351169384531754

6. Count the number of values in your new array that are below 7.

In [19]:
print("Count of values below 7:", (matrix < 7).sum())

AttributeError: 'bool' object has no attribute 'sum'

7. Make a numpy sequence that has the even numbers from 2 up to (and including) 20.

In [21]:
int_noise = n.random.randint(2,20,20)
int_noise

array([18,  4, 11,  8, 16, 11,  4,  7, 14,  3, 13, 10, 14,  4, 18, 14,  6,
       18,  9,  2])

8. Get the second and third rows of your array.

In [22]:
int_noise[1:3]

array([ 4, 11])

9. Compute the mean of the columns of your array.

In [24]:
int_noise.mean()

10.2